version: 2
updates:
  - package-ecosystem: "npm"
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "mike-weiner"
    labels:
      - "dependencies"
